from setuptools import find_packages,setup
import logentry
setup(
    name=logentry.__name__,
    version=logentry.__version__,
    packages=find_packages(),
    url='https://github.com/sainipray/django-logentry',
    author=logentry.__author__,
    author_email=logentry.__author_email__,
    description=logentry.__description__,
    license='MIT',
    include_package_data=True,
    platforms=['any'],
    zip_safe = False,
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Framework :: Django',
        'Framework :: Django :: 1.9',
        'Framework :: Django :: 1.10',
        'Framework :: Django :: 1.11',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Topic :: Software Development',
    ],
)
